#!/bin/bash

THREADS=8
SPECIES=Af

BASE_DIR=~/Af_rnaseq

RAW_DIR=$BASE_DIR/raw
TRIM_DIR=$BASE_DIR/trimmed
FASTQC_DIR=$BASE_DIR/fastqc
ASSEMBLY_DIR=$BASE_DIR/assembly

ADAPTER=$BASE_DIR/adapter_Af.fa

TRINITY_OUT=$ASSEMBLY_DIR/trinity_out
TRANSCRIPTOME=$TRINITY_OUT/Trinity.fasta

METADATA_DIR=Af/metadata
