#!/bin/bash

# usage:
# bash scripts/05_cdhit Ses/config.sh
# bash scripts/05_cdhit Afang/config.sh
# bash scripts/05_cdhit Lst/config.sh

source $1

cd-hit-est \
-i $TRINITY_FASTA \
-o $CDHIT_FASTA \
-c 0.9 \
-n 8 \
-T $THREADS \
-M 64000
